// <auto-generated />
using System;
using Forum_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum_MVC.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230921200450_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Forum_MVC.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AmountOfTopics")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfTopics = 5,
                            Name = "General Discussions",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfTopics = 3,
                            Name = "Coding Challenges and Solutions",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 3,
                            AmountOfTopics = 4,
                            Name = "Web Development",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 4,
                            AmountOfTopics = 9,
                            Name = "Mobile App Development",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 5,
                            AmountOfTopics = 21,
                            Name = "Game Development",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 6,
                            AmountOfTopics = 7,
                            Name = "Software Engineering",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 7,
                            AmountOfTopics = 2,
                            Name = "Programming Languages",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 8,
                            AmountOfTopics = 8,
                            Name = "Database Management",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 9,
                            AmountOfTopics = 19,
                            Name = "Algorithms and Data Structures",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 10,
                            AmountOfTopics = 6,
                            Name = "DevOps and Continuous Integration",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 11,
                            AmountOfTopics = 3,
                            Name = "Front-end Development",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 12,
                            AmountOfTopics = 4,
                            Name = "Back-end Development",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 13,
                            AmountOfTopics = 1,
                            Name = "Machine Learning and AI",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 14,
                            AmountOfTopics = 14,
                            Name = "Cybersecurity",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 15,
                            AmountOfTopics = 9,
                            Name = "Code Reviews and Feedback",
                            VisibilityStatus = "Suspended"
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PostStatisticsId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("PostStatisticsId")
                        .IsUnique()
                        .HasFilter("[PostStatisticsId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DislikeCount = 0,
                            LikeCount = 8,
                            PostId = 15,
                            Text = "Great post! AI in healthcare has so much potential.",
                            UserId = 16
                        },
                        new
                        {
                            Id = 2,
                            DislikeCount = 1,
                            LikeCount = 6,
                            PostId = 16,
                            Text = "I've always been fascinated by space travel. Thanks for sharing this.",
                            UserId = 17
                        },
                        new
                        {
                            Id = 3,
                            DislikeCount = 2,
                            LikeCount = 10,
                            PostId = 17,
                            Text = "Blockchain has the power to change everything. Exciting times ahead!",
                            UserId = 18
                        },
                        new
                        {
                            Id = 4,
                            DislikeCount = 0,
                            LikeCount = 7,
                            PostId = 18,
                            Text = "3D printing is a game-changer. Can't wait to see what's next.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 5,
                            DislikeCount = 1,
                            LikeCount = 9,
                            PostId = 19,
                            Text = "Remote work is here to stay. It's convenient and offers more flexibility.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 6,
                            DislikeCount = 3,
                            LikeCount = 11,
                            PostId = 20,
                            Text = "Sustainability is crucial in agriculture. We need to protect the environment.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 7,
                            DislikeCount = 2,
                            LikeCount = 12,
                            PostId = 21,
                            Text = "Electric vehicles are the future of transportation. Great article!",
                            UserId = 22
                        },
                        new
                        {
                            Id = 8,
                            DislikeCount = 1,
                            LikeCount = 9,
                            PostId = 22,
                            Text = "AR in education can make learning more engaging for students.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 9,
                            DislikeCount = 0,
                            LikeCount = 14,
                            PostId = 23,
                            Text = "Mars colonization would be a monumental achievement for humanity.",
                            UserId = 15
                        },
                        new
                        {
                            Id = 10,
                            DislikeCount = 2,
                            LikeCount = 10,
                            PostId = 24,
                            Text = "AI is changing the finance industry rapidly. Great insights!",
                            UserId = 16
                        },
                        new
                        {
                            Id = 11,
                            DislikeCount = 1,
                            LikeCount = 11,
                            PostId = 25,
                            Text = "UX design keeps evolving to create better user experiences.",
                            UserId = 12
                        },
                        new
                        {
                            Id = 12,
                            DislikeCount = 0,
                            LikeCount = 13,
                            PostId = 26,
                            Text = "Renewable energy storage is critical for a sustainable future.",
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            DislikeCount = 1,
                            LikeCount = 12,
                            PostId = 27,
                            Text = "Quantum cryptography is fascinating. It's the future of security.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 14,
                            DislikeCount = 3,
                            LikeCount = 15,
                            PostId = 28,
                            Text = "Agricultural technology is advancing rapidly. We need more innovation.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 15,
                            DislikeCount = 2,
                            LikeCount = 14,
                            PostId = 29,
                            Text = "Smart cities are the answer to urban challenges. Great article!",
                            UserId = 11
                        },
                        new
                        {
                            Id = 16,
                            DislikeCount = 0,
                            LikeCount = 16,
                            PostId = 30,
                            Text = "Ethical AI development is crucial for responsible technology.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 17,
                            DislikeCount = 1,
                            LikeCount = 13,
                            PostId = 31,
                            Text = "Biotechnology is revolutionizing healthcare and beyond.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 18,
                            DislikeCount = 3,
                            LikeCount = 15,
                            PostId = 31,
                            Text = "Private companies and government agencies both have roles in space exploration.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 19,
                            DislikeCount = 2,
                            LikeCount = 17,
                            PostId = 21,
                            Text = "Telemedicine is making healthcare more accessible to remote areas.",
                            UserId = 21
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostStatisticsId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TopicOfPostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PostStatisticsId")
                        .IsUnique()
                        .HasFilter("[PostStatisticsId] IS NOT NULL");

                    b.HasIndex("TopicOfPostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 9,
                            PostStatisticsId = 1,
                            Text = "Explore some fundamental machine learning algorithms for those new to the field.",
                            Title = "Machine Learning Algorithms for Beginners",
                            TopicOfPostId = 12,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 11,
                            PostStatisticsId = 2,
                            Text = "Tips for selecting the most suitable backend framework for your web application.",
                            Title = "Choosing the Right Backend Framework",
                            TopicOfPostId = 13,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            PostStatisticsId = 3,
                            Text = "Learn how to design VR experiences that captivate users and provide a sense of presence.",
                            Title = "Creating Immersive Virtual Reality Experiences",
                            TopicOfPostId = 14,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 7,
                            PostStatisticsId = 4,
                            Text = "A comprehensive guide to NLP techniques and libraries in the Python ecosystem.",
                            Title = "Natural Language Processing with Python",
                            TopicOfPostId = 15,
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            PostStatisticsId = 5,
                            Text = "Strategies and architectures to handle large volumes of traffic on your website.",
                            Title = "Scalability Strategies for High-Traffic Websites",
                            TopicOfPostId = 16,
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 14,
                            PostStatisticsId = 6,
                            Text = "Exploring security challenges and solutions in the context of 5G-connected IoT devices.",
                            Title = "IoT Security in the 5G Era",
                            TopicOfPostId = 17,
                            UserId = 8
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            PostStatisticsId = 7,
                            Text = "An overview and comparison of popular data visualization tools available today.",
                            Title = "Data Visualization Tools Comparison",
                            TopicOfPostId = 18,
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 14,
                            PostStatisticsId = 8,
                            Text = "Best practices and methodologies for conducting effective penetration tests.",
                            Title = "Penetration Testing Best Practices",
                            TopicOfPostId = 19,
                            UserId = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            PostStatisticsId = 9,
                            Text = "Tips and techniques for optimizing your e-commerce website for search engines.",
                            Title = "E-Commerce SEO Strategies",
                            TopicOfPostId = 20,
                            UserId = 11
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            PostStatisticsId = 10,
                            Text = "A guide to building cross-platform mobile apps using the Flutter framework.",
                            Title = "Cross-Platform Mobile App Development with Flutter",
                            TopicOfPostId = 21,
                            UserId = 12
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            PostStatisticsId = 11,
                            Text = "An exploration of the potential applications and challenges of quantum computing.",
                            Title = "Quantum Computing: Potential and Challenges",
                            TopicOfPostId = 22,
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            PostStatisticsId = 12,
                            Text = "Key principles for designing games that keep players engaged and entertained.",
                            Title = "Game Design Principles for Engaging Gameplay",
                            TopicOfPostId = 23,
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 9,
                            PostStatisticsId = 13,
                            Text = "A deep dive into building image recognition models using CNNs and deep learning.",
                            Title = "Image Recognition Using Convolutional Neural Networks",
                            TopicOfPostId = 24,
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            PostStatisticsId = 14,
                            Text = "Exploring renewable energy sources as a viable option for a greener and sustainable future.",
                            Title = "Renewable Energy Solutions for a Sustainable Future",
                            TopicOfPostId = 25,
                            UserId = 16
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 14,
                            PostStatisticsId = 15,
                            Text = "The role of cryptography in ensuring secure communication and data protection.",
                            Title = "Cryptography in Communication and Security",
                            TopicOfPostId = 26,
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            PostStatisticsId = 16,
                            Text = "Exploring how artificial intelligence is revolutionizing healthcare and medical diagnostics.",
                            Title = "The Impact of AI in Healthcare",
                            TopicOfPostId = 24,
                            UserId = 15
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 11,
                            PostStatisticsId = 17,
                            Text = "The challenges and potential future of space travel, including Mars exploration.",
                            Title = "Space Travel: Challenges and Future Prospects",
                            TopicOfPostId = 25,
                            UserId = 16
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            PostStatisticsId = 18,
                            Text = "The applications of blockchain technology beyond cryptocurrencies, such as supply chain and voting systems.",
                            Title = "Blockchain Technology: Beyond Cryptocurrency",
                            TopicOfPostId = 18,
                            UserId = 17
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            PostStatisticsId = 19,
                            Text = "Recent advancements in 3D printing technology and its impact on various industries.",
                            Title = "Advancements in 3D Printing",
                            TopicOfPostId = 18,
                            UserId = 18
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            PostStatisticsId = 20,
                            Text = "How remote and hybrid work models are shaping the future of work and office culture.",
                            Title = "The Future of Work: Remote and Hybrid Models",
                            TopicOfPostId = 25,
                            UserId = 19
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            PostStatisticsId = 21,
                            Text = "Exploring sustainable agriculture practices and their importance in food production.",
                            Title = "Sustainable Agriculture Practices",
                            TopicOfPostId = 8,
                            UserId = 20
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            PostStatisticsId = 22,
                            Text = "The growth and future of electric vehicles as an eco-friendly transportation option.",
                            Title = "Rise of Electric Vehicles (EVs)",
                            TopicOfPostId = 1,
                            UserId = 21
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            PostStatisticsId = 23,
                            Text = "How augmented reality is transforming education and enhancing learning experiences.",
                            Title = "Augmented Reality in Education",
                            TopicOfPostId = 22,
                            UserId = 22
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 11,
                            PostStatisticsId = 24,
                            Text = "The challenges and possibilities of human colonization on Mars.",
                            Title = "Mars Colonization: Challenges and Possibilities",
                            TopicOfPostId = 12,
                            UserId = 23
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 8,
                            PostStatisticsId = 25,
                            Text = "The role of AI in financial markets, risk assessment, and fraud detection.",
                            Title = "Artificial Intelligence in Finance",
                            TopicOfPostId = 26,
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 11,
                            PostStatisticsId = 26,
                            Text = "The evolution of UX design principles and their impact on digital products.",
                            Title = "The Evolution of User Experience (UX) Design",
                            TopicOfPostId = 22,
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            PostStatisticsId = 27,
                            Text = "Recent advances in energy storage technologies for renewable energy sources.",
                            Title = "Advances in Renewable Energy Storage",
                            TopicOfPostId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 14,
                            PostStatisticsId = 28,
                            Text = "The potential of quantum cryptography to revolutionize data security.",
                            Title = "The Future of Quantum Cryptography",
                            TopicOfPostId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            PostStatisticsId = 29,
                            Text = "Innovative technologies transforming agriculture and increasing crop yield.",
                            Title = "Agricultural Technology Innovations",
                            TopicOfPostId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 11,
                            PostStatisticsId = 30,
                            Text = "How smart city technologies are shaping the future of urban living.",
                            Title = "Smart Cities: Building the Future",
                            TopicOfPostId = 21,
                            UserId = 6
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            PostStatisticsId = 31,
                            Text = "Exploring ethical considerations in AI development and deployment.",
                            Title = "The Ethics of Artificial Intelligence",
                            TopicOfPostId = 20,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.PostStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PostStatistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DislikeCount = 3,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 2,
                            DislikeCount = 2,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 3,
                            DislikeCount = 1,
                            LikeCount = 12
                        },
                        new
                        {
                            Id = 4,
                            DislikeCount = 0,
                            LikeCount = 15
                        },
                        new
                        {
                            Id = 5,
                            DislikeCount = 2,
                            LikeCount = 11
                        },
                        new
                        {
                            Id = 6,
                            DislikeCount = 1,
                            LikeCount = 9
                        },
                        new
                        {
                            Id = 7,
                            DislikeCount = 0,
                            LikeCount = 14
                        },
                        new
                        {
                            Id = 8,
                            DislikeCount = 3,
                            LikeCount = 13
                        },
                        new
                        {
                            Id = 9,
                            DislikeCount = 2,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 10,
                            DislikeCount = 1,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 11,
                            DislikeCount = 0,
                            LikeCount = 7
                        },
                        new
                        {
                            Id = 12,
                            DislikeCount = 2,
                            LikeCount = 6
                        },
                        new
                        {
                            Id = 13,
                            DislikeCount = 1,
                            LikeCount = 9
                        },
                        new
                        {
                            Id = 14,
                            DislikeCount = 0,
                            LikeCount = 11
                        },
                        new
                        {
                            Id = 15,
                            DislikeCount = 2,
                            LikeCount = 14
                        },
                        new
                        {
                            Id = 16,
                            DislikeCount = 1,
                            LikeCount = 12
                        },
                        new
                        {
                            Id = 17,
                            DislikeCount = 2,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 18,
                            DislikeCount = 0,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 19,
                            DislikeCount = 1,
                            LikeCount = 7
                        },
                        new
                        {
                            Id = 20,
                            DislikeCount = 2,
                            LikeCount = 9
                        },
                        new
                        {
                            Id = 21,
                            DislikeCount = 3,
                            LikeCount = 15
                        },
                        new
                        {
                            Id = 22,
                            DislikeCount = 1,
                            LikeCount = 13
                        },
                        new
                        {
                            Id = 23,
                            DislikeCount = 0,
                            LikeCount = 11
                        },
                        new
                        {
                            Id = 24,
                            DislikeCount = 2,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 25,
                            DislikeCount = 1,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 26,
                            DislikeCount = 0,
                            LikeCount = 7
                        },
                        new
                        {
                            Id = 27,
                            DislikeCount = 2,
                            LikeCount = 6
                        },
                        new
                        {
                            Id = 28,
                            DislikeCount = 1,
                            LikeCount = 5
                        },
                        new
                        {
                            Id = 29,
                            DislikeCount = 0,
                            LikeCount = 4
                        },
                        new
                        {
                            Id = 30,
                            DislikeCount = 2,
                            LikeCount = 3
                        },
                        new
                        {
                            Id = 31,
                            DislikeCount = 1,
                            LikeCount = 2
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.TopicOfPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TopicsOfPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explore the basics of machine learning and its applications in real-world scenarios.",
                            Name = "Introduction to Machine Learning",
                            UserId = 1,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discover the latest trends and technologies shaping the world of web development in 2023.",
                            Name = "Web Development Trends in 2023",
                            UserId = 2,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A step-by-step guide for beginners to start learning Python programming from scratch.",
                            Name = "Beginner's Guide to Python Programming",
                            UserId = 3,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn essential cybersecurity practices to protect your digital assets and online privacy.",
                            Name = "Cybersecurity Best Practices",
                            UserId = 4,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Explore the principles and techniques behind creating visually appealing and user-friendly mobile app interfaces.",
                            Name = "The Art of Mobile App Design",
                            UserId = 5,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Delve into how data science can be used to extract valuable insights and drive decision-making in business.",
                            Name = "Data Science for Business Insights",
                            UserId = 6,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dive deep into popular JavaScript frameworks like React, Angular, and Vue.js to build dynamic web applications.",
                            Name = "Mastering JavaScript Frameworks",
                            UserId = 7,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Discover tips and tricks for maintaining a healthy lifestyle, including diet, exercise, and stress management.",
                            Name = "Healthy Lifestyle Habits",
                            UserId = 8,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Explore adrenaline-pumping travel destinations worldwide for adventure seekers.",
                            Name = "Travel Destinations for Adventure Enthusiasts",
                            UserId = 9,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Learn about the world of cryptocurrencies, investment strategies, and the latest developments in the crypto market.",
                            Name = "Investing in Cryptocurrencies",
                            UserId = 10,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Embark on a cosmic journey to explore the wonders of our universe, from distant galaxies to celestial phenomena.",
                            Name = "Exploring Space and Astronomy",
                            UserId = 11,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Explore how AI is transforming the healthcare industry and improving patient care.",
                            Name = "Artificial Intelligence in Healthcare",
                            UserId = 12,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Dive into the differences and similarities between frontend and backend development.",
                            Name = "Frontend vs. Backend Development",
                            UserId = 13,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Discover the potential applications and advancements in virtual reality technology.",
                            Name = "The Future of Virtual Reality",
                            UserId = 14,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Learn how machine learning is used to analyze and process human language.",
                            Name = "Machine Learning for Natural Language Processing",
                            UserId = 15,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Explore best practices for building web applications that can handle high traffic and scale efficiently.",
                            Name = "Building Scalable Web Applications",
                            UserId = 16,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Discuss the implications of 5G technology on the Internet of Things (IoT) ecosystem.",
                            Name = "The Impact of 5G on IoT",
                            UserId = 17,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 18,
                            Description = "A beginner's guide to creating meaningful visualizations from data.",
                            Name = "Getting Started with Data Visualization",
                            UserId = 18,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Learn about ethical hacking practices and how to secure your systems through penetration testing.",
                            Name = "Ethical Hacking and Penetration Testing",
                            UserId = 19,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Explore the dynamics of e-commerce, from online marketplaces to digital marketing strategies.",
                            Name = "The World of E-Commerce",
                            UserId = 20,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Discover tools and frameworks for developing mobile apps that work on multiple platforms.",
                            Name = "Building Cross-Platform Mobile Apps",
                            UserId = 21,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Learn about the principles of quantum computing and its potential to revolutionize computing.",
                            Name = "Introduction to Quantum Computing",
                            UserId = 22,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Explore the creative and technical aspects of designing engaging and immersive video games.",
                            Name = "The Art of Game Design",
                            UserId = 23,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Discover how machine learning models can identify and classify images with high accuracy.",
                            Name = "Machine Learning for Image Recognition",
                            UserId = 19,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Discuss sustainable energy options, such as solar, wind, and hydropower, for a greener future.",
                            Name = "Exploring Renewable Energy Sources",
                            UserId = 21,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Dive into the science of encryption and decryption, essential for secure communication and data protection.",
                            Name = "The World of Cryptography",
                            UserId = 23,
                            VisibilityStatus = "Active"
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PostStatisticsId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PostStatisticsId")
                        .IsUnique()
                        .HasFilter("[PostStatisticsId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "johndoe@example.com",
                            ImageUrl = "~/img/people/1.png",
                            Password = "StrongP@ssw0rd",
                            PostStatisticsId = 30,
                            Username = "JohnDoe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "janesmith@example.com",
                            ImageUrl = "~/img/people/people/1w.jpg",
                            Password = "Secure1234!",
                            PostStatisticsId = 20,
                            Username = "JaneSmith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mikejohnson@example.com",
                            ImageUrl = "~/img/people/2.jpg",
                            Password = "Pa$$w0rd#2023",
                            PostStatisticsId = 1,
                            Username = "MikeJohnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sarahbrown@example.com",
                            ImageUrl = "~/img/people/2w.jpg",
                            Password = "C0dingRocks!",
                            PostStatisticsId = 28,
                            Username = "SarahBrown"
                        },
                        new
                        {
                            Id = 5,
                            Email = "davidclark@example.com",
                            ImageUrl = "~/img/people/3.jpg",
                            Password = "TechGeek#123",
                            PostStatisticsId = 26,
                            Username = "DavidClark"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emilywilson@example.com",
                            ImageUrl = "~/img/people/3w.jpg",
                            Password = "Pr0gramm3r@",
                            PostStatisticsId = 2,
                            Username = "EmilyWilson"
                        },
                        new
                        {
                            Id = 7,
                            Email = "alexgarcia@example.com",
                            ImageUrl = "~/img/people/4.jpg",
                            Password = "D3v3l0pment$",
                            PostStatisticsId = 13,
                            Username = "AlexGarcia"
                        },
                        new
                        {
                            Id = 8,
                            Email = "lisadavis@example.com",
                            ImageUrl = "~/img/people/4w.jpg",
                            Password = "DataSecurity#1",
                            PostStatisticsId = 15,
                            Username = "LisaDavis"
                        },
                        new
                        {
                            Id = 9,
                            Email = "robertlee@example.com",
                            ImageUrl = "~/img/people/5.jpg",
                            Password = "H@ppyC0der",
                            PostStatisticsId = 18,
                            Username = "RobertLee"
                        },
                        new
                        {
                            Id = 10,
                            Email = "karenanderson@example.com",
                            ImageUrl = "~/img/people/5w.jpg",
                            Password = "Innov8tive&",
                            PostStatisticsId = 8,
                            Username = "KarenAnderson"
                        },
                        new
                        {
                            Id = 11,
                            Email = "marktaylor@example.com",
                            ImageUrl = "~/img/people/6.jpg",
                            Password = "MasterM1nd!",
                            PostStatisticsId = 27,
                            Username = "MarkTaylor"
                        },
                        new
                        {
                            Id = 12,
                            Email = "oliviawhite@example.com",
                            ImageUrl = "~/img/people/6w.jpg",
                            Password = "P@ssionateD3v",
                            PostStatisticsId = 14,
                            Username = "OliviaWhite"
                        },
                        new
                        {
                            Id = 13,
                            Email = "brianmiller@example.com",
                            ImageUrl = "~/img/people/7.jpg",
                            Password = "Creat1v3C0de",
                            PostStatisticsId = 11,
                            Username = "BrianMiller"
                        },
                        new
                        {
                            Id = 14,
                            Email = "sophiajohnson@example.com",
                            ImageUrl = "~/img/people/7w.jpg",
                            Password = "2FA4Security",
                            PostStatisticsId = 6,
                            Username = "SophiaJohnson"
                        },
                        new
                        {
                            Id = 15,
                            Email = "williamwilson@example.com",
                            ImageUrl = "~/img/people/8.jpg",
                            Password = "G3n!usC0d3r",
                            PostStatisticsId = 12,
                            Username = "WilliamWilson"
                        },
                        new
                        {
                            Id = 16,
                            Email = "jessicamoore@example.com",
                            ImageUrl = "~/img/people/8w.jpg",
                            Password = "DebugGuru#7",
                            PostStatisticsId = 17,
                            Username = "JessicaMoore"
                        },
                        new
                        {
                            Id = 17,
                            Email = "danielbrown@example.com",
                            ImageUrl = "~/img/people/9.jpg",
                            Password = "WebM@ster$2023",
                            PostStatisticsId = 18,
                            Username = "DanielBrown"
                        },
                        new
                        {
                            Id = 18,
                            Email = "emmamartinez@example.com",
                            ImageUrl = "~/img/people/9w.jpg",
                            Password = "0penS0urce",
                            PostStatisticsId = 23,
                            Username = "EmmaMartinez"
                        },
                        new
                        {
                            Id = 19,
                            Email = "michaelsmith@example.com",
                            ImageUrl = "~/img/people/10.jpg",
                            Password = "C0mput3rWh1z",
                            PostStatisticsId = 31,
                            Username = "MichaelSmith"
                        },
                        new
                        {
                            Id = 20,
                            Email = "avaharris@example.com",
                            ImageUrl = "~/img/people/10w.jpg",
                            Password = "H@rdw@r3L0v3r",
                            PostStatisticsId = 7,
                            Username = "AvaHarris"
                        },
                        new
                        {
                            Id = 21,
                            Email = "jamesjohnson@example.com",
                            ImageUrl = "~/img/people/11.jpg",
                            Password = "Alph@Num3ric",
                            PostStatisticsId = 9,
                            Username = "JamesJohnson"
                        },
                        new
                        {
                            Id = 22,
                            Email = "miataylor@example.com",
                            ImageUrl = "~/img/people/11w.jpg",
                            Password = "Art1f1c1@lInt3ll1g3nc3",
                            PostStatisticsId = 21,
                            Username = "MiaTaylor"
                        },
                        new
                        {
                            Id = 23,
                            Email = "ethanwilliams@example.com",
                            ImageUrl = "~/img/people/12.jpg",
                            Password = "B1gData&R3search",
                            PostStatisticsId = 1,
                            Username = "EthanWilliams"
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Comment", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Forum_MVC.Data.Entities.PostStatistics", "PostStatistics")
                        .WithOne()
                        .HasForeignKey("Forum_MVC.Data.Entities.Comment", "PostStatisticsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Forum_MVC.Data.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("PostStatistics");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Post", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.Category", "Categories")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Forum_MVC.Data.Entities.PostStatistics", "PostStatistics")
                        .WithOne()
                        .HasForeignKey("Forum_MVC.Data.Entities.Post", "PostStatisticsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Forum_MVC.Data.Entities.TopicOfPost", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicOfPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Forum_MVC.Data.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("PostStatistics");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.TopicOfPost", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.User", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.PostStatistics", "PostStatistics")
                        .WithOne()
                        .HasForeignKey("Forum_MVC.Data.Entities.User", "PostStatisticsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PostStatistics");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.TopicOfPost", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
