// <auto-generated />
using System;
using Forum_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum_MVC.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Forum_MVC.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AmountOfTopics")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfTopics = 5,
                            Name = "General Discussions",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfTopics = 3,
                            Name = "Coding Challenges and Solutions",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 3,
                            AmountOfTopics = 4,
                            Name = "Web Development",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 4,
                            AmountOfTopics = 9,
                            Name = "Mobile App Development",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 5,
                            AmountOfTopics = 21,
                            Name = "Game Development",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 6,
                            AmountOfTopics = 7,
                            Name = "Software Engineering",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 7,
                            AmountOfTopics = 2,
                            Name = "Programming Languages",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 8,
                            AmountOfTopics = 8,
                            Name = "Database Management",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 9,
                            AmountOfTopics = 19,
                            Name = "Algorithms and Data Structures",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 10,
                            AmountOfTopics = 6,
                            Name = "DevOps and Continuous Integration",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 11,
                            AmountOfTopics = 3,
                            Name = "Front-end Development",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 12,
                            AmountOfTopics = 4,
                            Name = "Back-end Development",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 13,
                            AmountOfTopics = 1,
                            Name = "Machine Learning and AI",
                            VisibilityStatus = "Suspended"
                        },
                        new
                        {
                            Id = 14,
                            AmountOfTopics = 14,
                            Name = "Cybersecurity",
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 15,
                            AmountOfTopics = 9,
                            Name = "Code Reviews and Feedback",
                            VisibilityStatus = "Suspended"
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PostStatisticsId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("PostStatisticsId")
                        .IsUnique()
                        .HasFilter("[PostStatisticsId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DislikeCount = 0,
                            LikeCount = 8,
                            PostId = 15,
                            Text = "Great post! AI in healthcare has so much potential.",
                            UserId = 16
                        },
                        new
                        {
                            Id = 2,
                            DislikeCount = 1,
                            LikeCount = 6,
                            PostId = 16,
                            Text = "I've always been fascinated by space travel. Thanks for sharing this.",
                            UserId = 17
                        },
                        new
                        {
                            Id = 3,
                            DislikeCount = 2,
                            LikeCount = 10,
                            PostId = 17,
                            Text = "Blockchain has the power to change everything. Exciting times ahead!",
                            UserId = 18
                        },
                        new
                        {
                            Id = 4,
                            DislikeCount = 0,
                            LikeCount = 7,
                            PostId = 18,
                            Text = "3D printing is a game-changer. Can't wait to see what's next.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 5,
                            DislikeCount = 1,
                            LikeCount = 9,
                            PostId = 19,
                            Text = "Remote work is here to stay. It's convenient and offers more flexibility.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 6,
                            DislikeCount = 3,
                            LikeCount = 11,
                            PostId = 20,
                            Text = "Sustainability is crucial in agriculture. We need to protect the environment.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 7,
                            DislikeCount = 2,
                            LikeCount = 12,
                            PostId = 21,
                            Text = "Electric vehicles are the future of transportation. Great article!",
                            UserId = 22
                        },
                        new
                        {
                            Id = 8,
                            DislikeCount = 1,
                            LikeCount = 9,
                            PostId = 22,
                            Text = "AR in education can make learning more engaging for students.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 9,
                            DislikeCount = 0,
                            LikeCount = 14,
                            PostId = 23,
                            Text = "Mars colonization would be a monumental achievement for humanity.",
                            UserId = 15
                        },
                        new
                        {
                            Id = 10,
                            DislikeCount = 2,
                            LikeCount = 10,
                            PostId = 24,
                            Text = "AI is changing the finance industry rapidly. Great insights!",
                            UserId = 16
                        },
                        new
                        {
                            Id = 11,
                            DislikeCount = 1,
                            LikeCount = 11,
                            PostId = 25,
                            Text = "UX design keeps evolving to create better user experiences.",
                            UserId = 12
                        },
                        new
                        {
                            Id = 12,
                            DislikeCount = 0,
                            LikeCount = 13,
                            PostId = 26,
                            Text = "Renewable energy storage is critical for a sustainable future.",
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            DislikeCount = 1,
                            LikeCount = 12,
                            PostId = 27,
                            Text = "Quantum cryptography is fascinating. It's the future of security.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 14,
                            DislikeCount = 3,
                            LikeCount = 15,
                            PostId = 28,
                            Text = "Agricultural technology is advancing rapidly. We need more innovation.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 15,
                            DislikeCount = 2,
                            LikeCount = 14,
                            PostId = 29,
                            Text = "Smart cities are the answer to urban challenges. Great article!",
                            UserId = 11
                        },
                        new
                        {
                            Id = 16,
                            DislikeCount = 0,
                            LikeCount = 16,
                            PostId = 30,
                            Text = "Ethical AI development is crucial for responsible technology.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 17,
                            DislikeCount = 1,
                            LikeCount = 13,
                            PostId = 31,
                            Text = "Biotechnology is revolutionizing healthcare and beyond.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 18,
                            DislikeCount = 3,
                            LikeCount = 15,
                            PostId = 31,
                            Text = "Private companies and government agencies both have roles in space exploration.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 19,
                            DislikeCount = 2,
                            LikeCount = 17,
                            PostId = 21,
                            Text = "Telemedicine is making healthcare more accessible to remote areas.",
                            UserId = 21
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostStatisticsId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TopicOfPostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PostStatisticsId")
                        .IsUnique()
                        .HasFilter("[PostStatisticsId] IS NOT NULL");

                    b.HasIndex("TopicOfPostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 9,
                            PostStatisticsId = 1,
                            Text = "Are you interested in diving into the exciting world of machine learning, but don't know where to start? You're in luck! In this comprehensive post, we'll explore some fundamental machine learning algorithms that are perfect for those who are new to the field. We'll break down complex concepts into easy-to-understand explanations, providing you with a solid foundation to build upon. From linear regression to decision trees and neural networks, you'll gain insights into various algorithms that power the world of artificial intelligence. So, whether you're a student looking to expand your knowledge or a professional considering a career change, this post has something for everyone. Get ready to embark on your machine learning journey!",
                            Title = "Machine Learning Algorithms for Beginners",
                            TopicOfPostId = 12,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 11,
                            PostStatisticsId = 2,
                            Text = "When it comes to building a web application, one of the most crucial decisions you'll face is selecting the right backend framework. The choice you make can significantly impact your project's success, scalability, and maintenance. In this extensively detailed post, we'll provide you with a wealth of information and tips to help you make an informed decision. We'll dive deep into the world of backend development, discussing the pros and cons of various frameworks, such as Node.js, Django, Ruby on Rails, and more. We'll also explore real-world use cases and provide valuable insights from experienced developers. By the end of this post, you'll be equipped with the knowledge needed to confidently choose the perfect backend framework for your web application, setting you up for success in your development journey.",
                            Title = "Choosing the Right Backend Framework",
                            TopicOfPostId = 13,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            PostStatisticsId = 3,
                            Text = "Virtual reality (VR) is changing the way we interact with digital content and experiences. Whether you're a game developer, a UX designer, or simply curious about the world of VR, this in-depth post is a must-read. We'll guide you through the process of designing and creating immersive VR experiences that captivate users and provide a true sense of presence. From the hardware and software requirements to best practices in 3D modeling and user interface design, we'll cover it all. You'll also learn about the latest VR technologies, including headsets, motion controllers, and haptic feedback devices. Get ready to embark on a journey into the world of virtual reality and discover how you can create unforgettable VR experiences.",
                            Title = "Creating Immersive Virtual Reality Experiences",
                            TopicOfPostId = 14,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 7,
                            PostStatisticsId = 4,
                            Text = "Natural Language Processing (NLP) is a fascinating field at the intersection of linguistics and computer science. In this extensive post, we'll take you on a deep dive into the world of NLP using the powerful Python programming language. Whether you're interested in sentiment analysis, chatbots, or language translation, NLP has applications in various domains, and Python is the go-to language for NLP enthusiasts. We'll start with the basics, covering tokenization, stemming, and part-of-speech tagging, and gradually progress to advanced topics like word embeddings and deep learning models. You'll also get hands-on experience with popular NLP libraries such as NLTK, spaCy, and Transformers. By the end of this post, you'll have the knowledge and tools to embark on your NLP projects and contribute to this exciting field.",
                            Title = "Natural Language Processing with Python",
                            TopicOfPostId = 15,
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            PostStatisticsId = 5,
                            Text = "Running a high-traffic website comes with its unique set of challenges. If you're a web developer or an IT professional responsible for managing web infrastructure, this comprehensive post is a goldmine of knowledge. We'll explore a wide range of strategies and architectures to ensure your website can handle large volumes of traffic without compromising on performance or reliability. From load balancing and caching techniques to content delivery networks (CDNs) and database optimization, we'll cover all the essential aspects of website scalability. You'll also learn about real-world case studies from popular websites that have successfully scaled to millions of users. By the end of this post, you'll be well-equipped to tackle the challenges of high-traffic websites and keep your users happy.",
                            Title = "Scalability Strategies for High-Traffic Websites",
                            TopicOfPostId = 16,
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 14,
                            PostStatisticsId = 6,
                            Text = "The Internet of Things (IoT) is transforming the way we interact with everyday objects, from smart thermostats to connected cars. However, this interconnectedness also brings security challenges that need to be addressed, especially in the context of 5G connectivity. In this extensively researched post, we'll delve deep into the world of IoT security. We'll explore the unique threats and vulnerabilities associated with IoT devices and networks and provide you with a comprehensive toolkit of security best practices and solutions. From device authentication and encryption to secure firmware updates and intrusion detection systems, you'll learn how to safeguard your IoT ecosystem. Additionally, we'll discuss the latest developments in 5G technology and how they impact IoT security. Whether you're a cybersecurity professional or an IoT enthusiast, this post will equip you with the knowledge and tools to ensure the security of your connected devices.",
                            Title = "IoT Security in the 5G Era",
                            TopicOfPostId = 17,
                            UserId = 8
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            PostStatisticsId = 7,
                            Text = "Data visualization is a powerful way to make sense of complex datasets and communicate insights effectively. With a plethora of data visualization tools available today, choosing the right one can be challenging. Fear not! In this extensive and meticulously crafted post, we'll provide you with a comprehensive comparison of popular data visualization tools. We'll explore the strengths and weaknesses of tools like Tableau, Power BI, D3.js, and many more. You'll also find detailed information on pricing, data integration capabilities, and user-friendliness. Whether you're a data analyst, a business intelligence professional, or a data science enthusiast, this post will help you make an informed decision and elevate your data visualization game. Get ready to create stunning and informative visualizations that drive better decision-making.",
                            Title = "Data Visualization Tools Comparison",
                            TopicOfPostId = 18,
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 14,
                            PostStatisticsId = 8,
                            Text = "Penetration testing, also known as ethical hacking, is a critical cybersecurity practice that helps organizations identify vulnerabilities and strengthen their defenses. In this meticulously detailed post, we'll dive deep into the world of penetration testing. Whether you're a cybersecurity professional or a curious IT enthusiast, you'll find valuable insights and best practices to enhance your skills. We'll cover the entire penetration testing lifecycle, from scoping and reconnaissance to exploitation and reporting. You'll learn about various tools and techniques used by penetration testers to uncover security weaknesses in networks, applications, and systems. We'll also discuss the importance of ethical conduct and responsible disclosure in the world of penetration testing. By the end of this post, you'll be well-prepared to embark on your journey as a skilled penetration tester and help secure digital assets.",
                            Title = "Penetration Testing Best Practices",
                            TopicOfPostId = 19,
                            UserId = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            PostStatisticsId = 9,
                            Text = "In the highly competitive world of e-commerce, search engine optimization (SEO) is a game-changer. If you run an online store or plan to launch one, this extensive post is your roadmap to SEO success. We'll take you on a comprehensive journey through the intricate world of e-commerce SEO strategies. From keyword research and on-page optimization to technical SEO and link-building techniques, you'll gain a deep understanding of how to rank higher in search engine results pages (SERPs). We'll also delve into e-commerce-specific SEO challenges and solutions, such as product page optimization and handling duplicate content. Additionally, you'll learn about the latest trends in SEO, including voice search and mobile optimization. By the end of this post, you'll be armed with the knowledge and strategies needed to drive organic traffic and boost sales for your e-commerce business.",
                            Title = "E-Commerce SEO Strategies",
                            TopicOfPostId = 20,
                            UserId = 11
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            PostStatisticsId = 10,
                            Text = "Building mobile apps for multiple platforms can be a daunting task, but it doesn't have to be. Enter Flutter, a powerful and versatile framework for cross-platform mobile app development. In this comprehensive and meticulously crafted post, we'll guide you through the exciting world of Flutter development. Whether you're an experienced app developer or just starting your journey, you'll find valuable insights and hands-on examples to accelerate your mobile app projects. We'll cover the fundamentals of Flutter, including widgets, layouts, and state management, and show you how to create stunning and responsive user interfaces. You'll also learn how to access device features and APIs, handle navigation, and optimize your app's performance. With Flutter's hot reload feature, you'll experience rapid development cycles, making it easier than ever to build and iterate on your app ideas. By the end of this post, you'll have the skills and confidence to develop cross-platform mobile apps that run seamlessly on iOS, Android, and beyond.",
                            Title = "Cross-Platform Mobile App Development with Flutter",
                            TopicOfPostId = 21,
                            UserId = 12
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            PostStatisticsId = 11,
                            Text = "Quantum computing is poised to revolutionize the world of computing, offering unprecedented computational power for solving complex problems. In this in-depth and meticulously researched post, we'll explore the potential applications and challenges of quantum computing. Whether you're a computer scientist, a physicist, or simply curious about the future of technology, you'll find this post enlightening. We'll delve into the core principles of quantum mechanics that underlie quantum computing and explain how qubits, superposition, and entanglement work. You'll also discover the potential impact of quantum computing on various fields, from cryptography and drug discovery to optimization problems and artificial intelligence. However, quantum computing isn't without its challenges, and we'll examine the roadblocks and limitations that researchers face. Join us on this journey into the quantum realm and gain a deep understanding of this groundbreaking technology.",
                            Title = "Quantum Computing: Potential and Challenges",
                            TopicOfPostId = 22,
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            PostStatisticsId = 12,
                            Text = "Creating captivating and enjoyable games is both an art and a science. If you're a game developer or aspiring to be one, this extensive post is a treasure trove of game design principles. We'll explore key principles and strategies that game designers use to create engaging gameplay experiences. From player motivation and game mechanics to level design and storytelling, we'll cover the essential aspects of game design. You'll gain insights into player psychology and learn how to keep players immersed and entertained. We'll also discuss case studies of popular games and dissect what makes them successful. Whether you're developing mobile games, console games, or virtual reality experiences, this post will equip you with the knowledge and techniques to craft memorable and enjoyable games that resonate with players.",
                            Title = "Game Design Principles for Engaging Gameplay",
                            TopicOfPostId = 23,
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 9,
                            PostStatisticsId = 13,
                            Text = "Image recognition is a fascinating field that has made significant advancements thanks to Convolutional Neural Networks (CNNs). In this extensively detailed post, we'll take you on a deep dive into the world of image recognition using CNNs and deep learning. Whether you're a computer vision enthusiast or a machine learning practitioner, you'll find valuable insights and practical knowledge in this post. We'll start with the basics, covering the inner workings of CNNs, including convolutional layers, pooling, and fully connected layers. You'll also learn about popular deep learning frameworks like TensorFlow and PyTorch, and how to implement CNNs for image recognition tasks. We'll explore real-world use cases, such as object detection, facial recognition, and image classification, showcasing the transformative power of CNNs in various domains. By the end of this post, you'll have the skills and confidence to embark on your image recognition projects and contribute to the advancement of computer vision.",
                            Title = "Image Recognition Using Convolutional Neural Networks",
                            TopicOfPostId = 24,
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            PostStatisticsId = 14,
                            Text = "The world is at a crossroads when it comes to energy consumption and environmental sustainability. Renewable energy sources offer a promising solution to mitigate climate change and ensure a greener and sustainable future. In this meticulously researched post, we'll explore renewable energy solutions and their potential to reshape our energy landscape. Whether you're an environmentalist, an energy professional, or simply curious about the future of energy, you'll find this post enlightening. We'll delve into various renewable energy sources, including solar, wind, hydro, and geothermal power, and discuss their advantages and challenges. You'll also learn about cutting-edge technologies, such as energy storage systems and grid integration, that play a crucial role in harnessing renewable energy. Additionally, we'll examine real-world examples of renewable energy projects and their impact on communities and economies. Join us on this journey to a sustainable future and discover how renewable energy can power the world.",
                            Title = "Renewable Energy Solutions for a Sustainable Future",
                            TopicOfPostId = 25,
                            UserId = 16
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 14,
                            PostStatisticsId = 15,
                            Text = "Cryptography is the cornerstone of secure communication and data protection in the digital age. In this extensively researched post, we'll explore the role of cryptography in ensuring the confidentiality, integrity, and authenticity of information. Whether you're a cybersecurity professional, a software developer, or simply interested in the science of secrecy, you'll find this post illuminating. We'll start with the fundamentals of cryptography, including encryption algorithms, key management, and digital signatures. You'll gain a deep understanding of how cryptographic techniques work and their applications in various domains, from secure messaging and online banking to digital identity and blockchain technology. We'll also discuss the latest developments in post-quantum cryptography and the challenges posed by quantum computers. By the end of this post, you'll have a solid grasp of cryptography's vital role in modern communication and security.",
                            Title = "Cryptography in Communication and Security",
                            TopicOfPostId = 26,
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            PostStatisticsId = 16,
                            Text = "Artificial Intelligence (AI) is revolutionizing the healthcare industry, offering new possibilities for diagnostics, treatment, and patient care. In this comprehensive post, we'll explore how AI is transforming healthcare and shaping its future. Whether you're a healthcare professional, a data scientist, or simply curious about the intersection of technology and healthcare, you'll find this post enlightening. We'll delve into various applications of AI in healthcare, including medical imaging, predictive analytics, and drug discovery. You'll discover how AI-powered algorithms can analyze medical images with remarkable accuracy and assist in early disease detection. We'll also discuss the ethical considerations and regulatory challenges surrounding AI in healthcare. Additionally, you'll learn about real-world case studies and success stories of AI implementation in hospitals and medical research. Join us on this journey into the world of AI in healthcare and explore the profound impact it's having on patient outcomes and medical advancements.",
                            Title = "The Impact of AI in Healthcare",
                            TopicOfPostId = 24,
                            UserId = 15
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 11,
                            PostStatisticsId = 17,
                            Text = "Space travel has always captured the imagination of humanity, and it's now closer to reality than ever before. In this extensively researched post, we'll explore the challenges and potential future of space travel, including the ambitious goal of human colonization on Mars. Whether you're a space enthusiast, an aerospace engineer, or simply curious about the cosmos, you'll find this post captivating. We'll delve into the technical and logistical challenges of space travel, from rocket propulsion and radiation protection to life support systems and interplanetary navigation. You'll also learn about the latest developments in space exploration, including the missions to Mars and the search for extraterrestrial life. Additionally, we'll discuss the societal and ethical implications of space travel, including its impact on Earth's environment and the potential for human settlement on other planets. Join us on this cosmic journey and uncover the exciting possibilities and challenges that await us in the final frontier.",
                            Title = "Space Travel: Challenges and Future Prospects",
                            TopicOfPostId = 25,
                            UserId = 16
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            PostStatisticsId = 18,
                            Text = "Blockchain technology, originally designed for cryptocurrencies like Bitcoin, has evolved to find applications in various industries beyond finance. In this meticulously researched post, we'll explore the diverse uses of blockchain technology and how it's reshaping processes and systems. Whether you're a blockchain enthusiast, a business professional, or simply curious about decentralized technologies, you'll find this post illuminating. We'll delve into the fundamental concepts of blockchain, including distributed ledgers, smart contracts, and consensus algorithms. You'll gain insights into how blockchain is transforming supply chain management, healthcare, voting systems, and more. We'll also discuss the challenges and limitations of blockchain, including scalability and regulatory considerations. Additionally, you'll learn about real-world case studies of blockchain implementations and their impact on transparency and security. Join us on this journey to discover the profound impact of blockchain technology beyond cryptocurrency.",
                            Title = "Blockchain Technology: Beyond Cryptocurrency",
                            TopicOfPostId = 18,
                            UserId = 17
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            PostStatisticsId = 19,
                            Text = "3D printing technology has come a long way since its inception, and it's revolutionizing industries ranging from manufacturing to healthcare. In this comprehensive post, we'll explore the recent advancements in 3D printing and their impact on various sectors. Whether you're an engineer, a designer, or simply intrigued by the possibilities of additive manufacturing, you'll find this post enlightening. We'll delve into the core principles of 3D printing, including different printing techniques and materials. You'll discover how 3D printing is transforming industries such as aerospace, automotive, and healthcare, with applications like rapid prototyping, customized medical implants, and even 3D-printed food. We'll also discuss the future of 3D printing, including innovations in multi-material printing and the potential for on-demand manufacturing. By the end of this post, you'll have a deep understanding of the exciting advancements in 3D printing and their implications for the future.",
                            Title = "Advancements in 3D Printing",
                            TopicOfPostId = 18,
                            UserId = 18
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            PostStatisticsId = 20,
                            Text = "The traditional workplace is undergoing a significant transformation, driven by advances in technology and changing attitudes towards work. In this extensively researched post, we'll explore the future of work and how remote and hybrid work models are reshaping the way we work and collaborate. Whether you're a business leader, an HR professional, or an employee navigating the evolving work landscape, you'll find this post insightful. We'll delve into the factors driving the shift towards remote and hybrid work, including the rise of digital tools and the importance of work-life balance. You'll discover strategies for effective remote team management, fostering employee engagement, and maintaining productivity in a remote or hybrid work environment. We'll also discuss the implications of this shift on office space design, corporate culture, and the gig economy. Join us on this exploration of the future of work and gain valuable insights into how organizations and individuals can thrive in the evolving work landscape.",
                            Title = "The Future of Work: Remote and Hybrid Models",
                            TopicOfPostId = 25,
                            UserId = 19
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            PostStatisticsId = 21,
                            Text = "Agriculture plays a pivotal role in feeding the global population, but it also has a significant impact on the environment. In this meticulously researched post, we'll explore sustainable agriculture practices and their importance in ensuring food production while preserving our planet. Whether you're a farmer, an environmentalist, or simply interested in the future of food, you'll find this post enlightening. We'll delve into sustainable farming techniques, including organic farming, crop rotation, and precision agriculture. You'll discover how these practices reduce the environmental footprint of agriculture, conserve natural resources, and promote biodiversity. We'll also discuss the role of technology in sustainable agriculture, from IoT sensors and drones to data analytics and genetic engineering. Additionally, you'll learn about the benefits of sustainable agriculture for farmers, consumers, and the planet as a whole. Join us on this journey to explore the practices that can help feed the world while protecting the Earth.",
                            Title = "Sustainable Agriculture Practices",
                            TopicOfPostId = 8,
                            UserId = 20
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            PostStatisticsId = 22,
                            Text = "The automotive industry is undergoing a profound transformation with the rise of Electric Vehicles (EVs). In this extensively researched post, we'll explore the growth and future prospects of EVs as an eco-friendly and sustainable transportation option. Whether you're an automotive enthusiast, an environmental advocate, or considering an EV for your next vehicle, you'll find this post illuminating. We'll delve into the technology behind electric vehicles, including battery chemistry, charging infrastructure, and electric drivetrains. You'll discover the environmental benefits of EVs, including reduced greenhouse gas emissions and air pollution. We'll also discuss the challenges and opportunities of EV adoption, such as range anxiety and government incentives. Additionally, you'll learn about the latest advancements in EV technology, from autonomous driving features to solid-state batteries. Join us on this journey to explore the electric vehicle revolution and the role it plays in a greener and more sustainable future.",
                            Title = "Rise of Electric Vehicles (EVs)",
                            TopicOfPostId = 1,
                            UserId = 21
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            PostStatisticsId = 23,
                            Text = "Education is evolving, thanks to the integration of Augmented Reality (AR) technology. In this comprehensive post, we'll explore how AR is transforming education and enhancing learning experiences. Whether you're an educator, a student, or simply curious about the future of learning, you'll find this post enlightening. We'll delve into the potential of AR in education, from interactive textbooks and virtual field trips to immersive language learning and laboratory simulations. You'll discover how AR engages students, improves retention, and fosters a deeper understanding of complex subjects. We'll also discuss practical examples of AR applications in different educational settings, from K-12 schools to higher education institutions. Additionally, you'll learn about the challenges and considerations of implementing AR in education, including device compatibility and content creation. Join us on this exploration of Augmented Reality in education and discover the exciting possibilities it offers for learners of all ages.",
                            Title = "Augmented Reality in Education",
                            TopicOfPostId = 22,
                            UserId = 22
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 11,
                            PostStatisticsId = 24,
                            Text = "The dream of human colonization on Mars has captured the imagination of space enthusiasts and scientists alike. In this meticulously researched post, we'll explore the challenges and possibilities of making Mars colonization a reality. Whether you're a space aficionado, an aerospace engineer, or simply curious about the future of space exploration, you'll find this post captivating. We'll delve into the technical and logistical challenges of sending humans to Mars, including spacecraft design, life support systems, and radiation protection. You'll discover the potential benefits of Mars colonization, from scientific discoveries to the expansion of human civilization beyond Earth. We'll also discuss the ethical and psychological aspects of long-duration space missions and the challenges of sustaining life on the Red Planet. Additionally, you'll learn about the latest developments in Mars exploration, including the missions planned by space agencies and private companies. Join us on this cosmic journey and explore the exciting possibilities and challenges of establishing a human presence on Mars.",
                            Title = "Mars Colonization: Challenges and Possibilities",
                            TopicOfPostId = 11,
                            UserId = 23
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 8,
                            PostStatisticsId = 25,
                            Text = "The financial industry is undergoing a profound transformation, thanks to the integration of Artificial Intelligence (AI). In this meticulously researched post, we'll explore the role of AI in financial markets, risk assessment, and fraud detection. Whether you're a finance professional, a data scientist, or simply interested in the intersection of technology and finance, you'll find this post illuminating. We'll delve into the various applications of AI in finance, from algorithmic trading and robo-advisors to credit scoring and fraud prevention. You'll discover how AI-powered algorithms analyze vast datasets with speed and precision, making informed decisions in milliseconds. We'll also discuss the challenges and ethical considerations of AI in finance, including bias and transparency. Additionally, you'll learn about the regulatory landscape and the future of AI in the financial industry. Join us on this exploration of Artificial Intelligence in finance and uncover the transformative impact it's having on the world of money.",
                            Title = "Artificial Intelligence in Finance",
                            TopicOfPostId = 26,
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 11,
                            PostStatisticsId = 26,
                            Text = "User Experience (UX) design has evolved significantly in recent years, shaping the way we interact with digital products and services. In this comprehensive post, we'll explore the evolution of UX design principles and their impact on user interfaces. Whether you're a UX designer, a product manager, or simply curious about the world of design, you'll find this post insightful. We'll delve into the history of UX design, from the early days of usability testing to the emergence of user-centered design principles. You'll discover how user research, information architecture, and usability testing have become integral parts of the design process. We'll also discuss the impact of mobile devices and responsive design on UX, as well as the rise of voice interfaces and conversational UX. Additionally, you'll learn about the latest trends in UX, including augmented reality (AR) and virtual reality (VR) experiences. Join us on this journey through the evolution of UX design and gain a deep understanding of how user-centered principles are shaping the digital world.",
                            Title = "The Evolution of User Experience (UX) Design",
                            TopicOfPostId = 22,
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            PostStatisticsId = 27,
                            Text = "Renewable energy sources like solar and wind power are crucial for a sustainable future, but they are intermittent by nature. Energy storage technologies play a pivotal role in harnessing renewable energy effectively. In this meticulously researched post, we'll explore the recent advances in energy storage and their impact on the transition to renewable energy. Whether you're an environmental advocate, an energy professional, or simply interested in the future of clean energy, you'll find this post enlightening. We'll delve into the various energy storage solutions, from lithium-ion batteries and pumped hydro storage to cutting-edge technologies like flow batteries and thermal energy storage. You'll discover how energy storage can stabilize the grid, store excess energy for later use, and enable the integration of renewable sources into the energy mix. We'll also discuss the economic and environmental benefits of energy storage and its role in reducing greenhouse gas emissions. Join us on this journey to explore the exciting advancements in renewable energy storage and their potential to reshape our energy landscape.",
                            Title = "Advances in Renewable Energy Storage",
                            TopicOfPostId = 25,
                            UserId = 3
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 14,
                            PostStatisticsId = 28,
                            Text = "Quantum cryptography is poised to revolutionize data security by harnessing the principles of quantum mechanics to create unbreakable encryption. In this extensively researched post, we'll explore the potential of quantum cryptography and its implications for data protection. Whether you're a cybersecurity professional, a researcher, or simply intrigued by the cutting-edge of cryptography, you'll find this post illuminating. We'll delve into the core concepts of quantum cryptography, including quantum key distribution and quantum-resistant algorithms. You'll discover how quantum properties such as superposition and entanglement can be leveraged to secure communications. We'll also discuss the challenges and limitations of quantum cryptography, including the race to build practical quantum computers and the threat they pose to traditional encryption. Additionally, you'll learn about real-world implementations of quantum cryptography and its use cases in industries like finance and government. Join us on this exploration of the future of data security and uncover how quantum cryptography is reshaping the landscape of encryption.",
                            Title = "The Future of Quantum Cryptography",
                            TopicOfPostId = 15,
                            UserId = 4
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            PostStatisticsId = 29,
                            Text = "Agriculture is undergoing a technological revolution, with innovative solutions reshaping the way we produce food and manage crops. In this comprehensive post, we'll explore the agricultural technology innovations that are increasing efficiency and sustainability in farming. Whether you're a farmer, an agtech enthusiast, or simply interested in the future of agriculture, you'll find this post insightful. We'll delve into cutting-edge technologies, such as precision agriculture, IoT sensors, and autonomous machinery, that are transforming farming practices. You'll discover how data analytics and AI-powered tools optimize crop yield, reduce resource usage, and mitigate environmental impact. We'll also discuss vertical farming and hydroponics as alternative approaches to traditional agriculture, addressing issues of land scarcity and water conservation. Additionally, you'll learn about the role of blockchain in supply chain transparency and food traceability. Join us on this journey through the world of agricultural technology and gain a deeper understanding of how innovation is shaping the future of food production.",
                            Title = "Agricultural Technology Innovations",
                            TopicOfPostId = 9,
                            UserId = 5
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 11,
                            PostStatisticsId = 30,
                            Text = "The future of urban living is here, and it's smart. In this extensively researched post, we'll explore how smart city technologies are transforming urban environments and improving the quality of life for residents. Whether you're an urban planner, a tech enthusiast, or simply curious about the cities of tomorrow, you'll find this post enlightening. We'll delve into the core components of smart cities, from IoT sensors and data analytics to connected infrastructure and sustainable transportation. You'll discover how smart city initiatives enhance public services, reduce energy consumption, and promote environmental sustainability. We'll also discuss real-world examples of smart city projects around the globe, showcasing the impact of technology on urban development. Additionally, you'll learn about the challenges and considerations of building smart cities, including privacy concerns and digital equity. Join us on this exploration of the future of urban living and discover how smart cities are revolutionizing the way we experience city life.",
                            Title = "Smart Cities: Building the Future",
                            TopicOfPostId = 21,
                            UserId = 6
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            PostStatisticsId = 31,
                            Text = "The rapid advancement of Artificial Intelligence (AI) raises important ethical questions that society must address. In this comprehensive post, we'll explore the ethical considerations surrounding AI development and deployment. Whether you're an AI researcher, an ethicist, or simply interested in the intersection of technology and morality, you'll find this post thought-provoking. We'll delve into the ethical principles that underlie AI, including fairness, transparency, and accountability. You'll discover the challenges posed by biased algorithms, autonomous weapons, and AI-driven decision-making. We'll also discuss the role of regulation and governance in ensuring ethical AI practices and preventing AI misuse. Additionally, you'll learn about the philosophical debates surrounding AI and consciousness, as well as the potential impact of AI on employment and society. Join us on this exploration of the ethical complexities of AI and gain a deeper understanding of the moral questions that AI raises.",
                            Title = "The Ethics of Artificial Intelligence",
                            TopicOfPostId = 20,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.PostStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PostStatistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DislikeCount = 3,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 2,
                            DislikeCount = 2,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 3,
                            DislikeCount = 1,
                            LikeCount = 12
                        },
                        new
                        {
                            Id = 4,
                            DislikeCount = 0,
                            LikeCount = 15
                        },
                        new
                        {
                            Id = 5,
                            DislikeCount = 2,
                            LikeCount = 11
                        },
                        new
                        {
                            Id = 6,
                            DislikeCount = 1,
                            LikeCount = 9
                        },
                        new
                        {
                            Id = 7,
                            DislikeCount = 0,
                            LikeCount = 14
                        },
                        new
                        {
                            Id = 8,
                            DislikeCount = 3,
                            LikeCount = 13
                        },
                        new
                        {
                            Id = 9,
                            DislikeCount = 2,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 10,
                            DislikeCount = 1,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 11,
                            DislikeCount = 0,
                            LikeCount = 7
                        },
                        new
                        {
                            Id = 12,
                            DislikeCount = 2,
                            LikeCount = 6
                        },
                        new
                        {
                            Id = 13,
                            DislikeCount = 1,
                            LikeCount = 9
                        },
                        new
                        {
                            Id = 14,
                            DislikeCount = 0,
                            LikeCount = 11
                        },
                        new
                        {
                            Id = 15,
                            DislikeCount = 2,
                            LikeCount = 14
                        },
                        new
                        {
                            Id = 16,
                            DislikeCount = 1,
                            LikeCount = 12
                        },
                        new
                        {
                            Id = 17,
                            DislikeCount = 2,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 18,
                            DislikeCount = 0,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 19,
                            DislikeCount = 1,
                            LikeCount = 7
                        },
                        new
                        {
                            Id = 20,
                            DislikeCount = 2,
                            LikeCount = 9
                        },
                        new
                        {
                            Id = 21,
                            DislikeCount = 3,
                            LikeCount = 15
                        },
                        new
                        {
                            Id = 22,
                            DislikeCount = 1,
                            LikeCount = 13
                        },
                        new
                        {
                            Id = 23,
                            DislikeCount = 0,
                            LikeCount = 11
                        },
                        new
                        {
                            Id = 24,
                            DislikeCount = 2,
                            LikeCount = 10
                        },
                        new
                        {
                            Id = 25,
                            DislikeCount = 1,
                            LikeCount = 8
                        },
                        new
                        {
                            Id = 26,
                            DislikeCount = 0,
                            LikeCount = 7
                        },
                        new
                        {
                            Id = 27,
                            DislikeCount = 2,
                            LikeCount = 6
                        },
                        new
                        {
                            Id = 28,
                            DislikeCount = 1,
                            LikeCount = 5
                        },
                        new
                        {
                            Id = 29,
                            DislikeCount = 0,
                            LikeCount = 4
                        },
                        new
                        {
                            Id = 30,
                            DislikeCount = 2,
                            LikeCount = 3
                        },
                        new
                        {
                            Id = 31,
                            DislikeCount = 1,
                            LikeCount = 2
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.TopicOfPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TopicsOfPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explore the basics of machine learning and its applications in real-world scenarios.",
                            Name = "Introduction to Machine Learning",
                            UserId = 1,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discover the latest trends and technologies shaping the world of web development in 2023.",
                            Name = "Web Development Trends in 2023",
                            UserId = 2,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A step-by-step guide for beginners to start learning Python programming from scratch.",
                            Name = "Beginner's Guide to Python Programming",
                            UserId = 3,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn essential cybersecurity practices to protect your digital assets and online privacy.",
                            Name = "Cybersecurity Best Practices",
                            UserId = 4,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Explore the principles and techniques behind creating visually appealing and user-friendly mobile app interfaces.",
                            Name = "The Art of Mobile App Design",
                            UserId = 5,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Delve into how data science can be used to extract valuable insights and drive decision-making in business.",
                            Name = "Data Science for Business Insights",
                            UserId = 6,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dive deep into popular JavaScript frameworks like React, Angular, and Vue.js to build dynamic web applications.",
                            Name = "Mastering JavaScript Frameworks",
                            UserId = 7,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Discover tips and tricks for maintaining a healthy lifestyle, including diet, exercise, and stress management.",
                            Name = "Healthy Lifestyle Habits",
                            UserId = 8,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Explore adrenaline-pumping travel destinations worldwide for adventure seekers.",
                            Name = "Travel Destinations for Adventure Enthusiasts",
                            UserId = 9,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Learn about the world of cryptocurrencies, investment strategies, and the latest developments in the crypto market.",
                            Name = "Investing in Cryptocurrencies",
                            UserId = 10,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Embark on a cosmic journey to explore the wonders of our universe, from distant galaxies to celestial phenomena.",
                            Name = "Exploring Space and Astronomy",
                            UserId = 11,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Explore how AI is transforming the healthcare industry and improving patient care.",
                            Name = "Artificial Intelligence in Healthcare",
                            UserId = 12,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Dive into the differences and similarities between frontend and backend development.",
                            Name = "Frontend vs. Backend Development",
                            UserId = 13,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Discover the potential applications and advancements in virtual reality technology.",
                            Name = "The Future of Virtual Reality",
                            UserId = 14,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Learn how machine learning is used to analyze and process human language.",
                            Name = "Machine Learning for Natural Language Processing",
                            UserId = 15,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Explore best practices for building web applications that can handle high traffic and scale efficiently.",
                            Name = "Building Scalable Web Applications",
                            UserId = 16,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Discuss the implications of 5G technology on the Internet of Things (IoT) ecosystem.",
                            Name = "The Impact of 5G on IoT",
                            UserId = 17,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 18,
                            Description = "A beginner's guide to creating meaningful visualizations from data.",
                            Name = "Getting Started with Data Visualization",
                            UserId = 18,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Learn about ethical hacking practices and how to secure your systems through penetration testing.",
                            Name = "Ethical Hacking and Penetration Testing",
                            UserId = 19,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Explore the dynamics of e-commerce, from online marketplaces to digital marketing strategies.",
                            Name = "The World of E-Commerce",
                            UserId = 20,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Discover tools and frameworks for developing mobile apps that work on multiple platforms.",
                            Name = "Building Cross-Platform Mobile Apps",
                            UserId = 21,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Learn about the principles of quantum computing and its potential to revolutionize computing.",
                            Name = "Introduction to Quantum Computing",
                            UserId = 22,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Explore the creative and technical aspects of designing engaging and immersive video games.",
                            Name = "The Art of Game Design",
                            UserId = 23,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Discover how machine learning models can identify and classify images with high accuracy.",
                            Name = "Machine Learning for Image Recognition",
                            UserId = 19,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Discuss sustainable energy options, such as solar, wind, and hydropower, for a greener future.",
                            Name = "Exploring Renewable Energy Sources",
                            UserId = 21,
                            VisibilityStatus = "Active"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Dive into the science of encryption and decryption, essential for secure communication and data protection.",
                            Name = "The World of Cryptography",
                            UserId = 23,
                            VisibilityStatus = "Active"
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PostStatisticsId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PostStatisticsId")
                        .IsUnique()
                        .HasFilter("[PostStatisticsId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "johndoe@example.com",
                            ImageUrl = "~/img/people/1.png",
                            Password = "StrongP@ssw0rd",
                            PostStatisticsId = 30,
                            Username = "JohnDoe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "janesmith@example.com",
                            ImageUrl = "~/img/people/people/1w.jpg",
                            Password = "Secure1234!",
                            PostStatisticsId = 20,
                            Username = "JaneSmith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mikejohnson@example.com",
                            ImageUrl = "~/img/people/2.jpg",
                            Password = "Pa$$w0rd#2023",
                            PostStatisticsId = 1,
                            Username = "MikeJohnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sarahbrown@example.com",
                            ImageUrl = "~/img/people/2w.jpg",
                            Password = "C0dingRocks!",
                            PostStatisticsId = 28,
                            Username = "SarahBrown"
                        },
                        new
                        {
                            Id = 5,
                            Email = "davidclark@example.com",
                            ImageUrl = "~/img/people/3.jpg",
                            Password = "TechGeek#123",
                            PostStatisticsId = 26,
                            Username = "DavidClark"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emilywilson@example.com",
                            ImageUrl = "~/img/people/3w.jpg",
                            Password = "Pr0gramm3r@",
                            PostStatisticsId = 2,
                            Username = "EmilyWilson"
                        },
                        new
                        {
                            Id = 7,
                            Email = "alexgarcia@example.com",
                            ImageUrl = "~/img/people/4.jpg",
                            Password = "D3v3l0pment$",
                            PostStatisticsId = 13,
                            Username = "AlexGarcia"
                        },
                        new
                        {
                            Id = 8,
                            Email = "lisadavis@example.com",
                            ImageUrl = "~/img/people/4w.jpg",
                            Password = "DataSecurity#1",
                            PostStatisticsId = 15,
                            Username = "LisaDavis"
                        },
                        new
                        {
                            Id = 9,
                            Email = "robertlee@example.com",
                            ImageUrl = "~/img/people/5.jpg",
                            Password = "H@ppyC0der",
                            PostStatisticsId = 18,
                            Username = "RobertLee"
                        },
                        new
                        {
                            Id = 10,
                            Email = "karenanderson@example.com",
                            ImageUrl = "~/img/people/5w.jpg",
                            Password = "Innov8tive&",
                            PostStatisticsId = 8,
                            Username = "KarenAnderson"
                        },
                        new
                        {
                            Id = 11,
                            Email = "marktaylor@example.com",
                            ImageUrl = "~/img/people/6.jpg",
                            Password = "MasterM1nd!",
                            PostStatisticsId = 27,
                            Username = "MarkTaylor"
                        },
                        new
                        {
                            Id = 12,
                            Email = "oliviawhite@example.com",
                            ImageUrl = "~/img/people/6w.jpg",
                            Password = "P@ssionateD3v",
                            PostStatisticsId = 14,
                            Username = "OliviaWhite"
                        },
                        new
                        {
                            Id = 13,
                            Email = "brianmiller@example.com",
                            ImageUrl = "~/img/people/7.jpg",
                            Password = "Creat1v3C0de",
                            PostStatisticsId = 11,
                            Username = "BrianMiller"
                        },
                        new
                        {
                            Id = 14,
                            Email = "sophiajohnson@example.com",
                            ImageUrl = "~/img/people/7w.jpg",
                            Password = "2FA4Security",
                            PostStatisticsId = 6,
                            Username = "SophiaJohnson"
                        },
                        new
                        {
                            Id = 15,
                            Email = "williamwilson@example.com",
                            ImageUrl = "~/img/people/8.jpg",
                            Password = "G3n!usC0d3r",
                            PostStatisticsId = 12,
                            Username = "WilliamWilson"
                        },
                        new
                        {
                            Id = 16,
                            Email = "jessicamoore@example.com",
                            ImageUrl = "~/img/people/8w.jpg",
                            Password = "DebugGuru#7",
                            PostStatisticsId = 17,
                            Username = "JessicaMoore"
                        },
                        new
                        {
                            Id = 17,
                            Email = "danielbrown@example.com",
                            ImageUrl = "~/img/people/9.jpg",
                            Password = "WebM@ster$2023",
                            PostStatisticsId = 18,
                            Username = "DanielBrown"
                        },
                        new
                        {
                            Id = 18,
                            Email = "emmamartinez@example.com",
                            ImageUrl = "~/img/people/9w.jpg",
                            Password = "0penS0urce",
                            PostStatisticsId = 23,
                            Username = "EmmaMartinez"
                        },
                        new
                        {
                            Id = 19,
                            Email = "michaelsmith@example.com",
                            ImageUrl = "~/img/people/10.jpg",
                            Password = "C0mput3rWh1z",
                            PostStatisticsId = 31,
                            Username = "MichaelSmith"
                        },
                        new
                        {
                            Id = 20,
                            Email = "avaharris@example.com",
                            ImageUrl = "~/img/people/10w.jpg",
                            Password = "H@rdw@r3L0v3r",
                            PostStatisticsId = 7,
                            Username = "AvaHarris"
                        },
                        new
                        {
                            Id = 21,
                            Email = "jamesjohnson@example.com",
                            ImageUrl = "~/img/people/11.jpg",
                            Password = "Alph@Num3ric",
                            PostStatisticsId = 9,
                            Username = "JamesJohnson"
                        },
                        new
                        {
                            Id = 22,
                            Email = "miataylor@example.com",
                            ImageUrl = "~/img/people/11w.jpg",
                            Password = "Art1f1c1@lInt3ll1g3nc3",
                            PostStatisticsId = 21,
                            Username = "MiaTaylor"
                        },
                        new
                        {
                            Id = 23,
                            Email = "ethanwilliams@example.com",
                            ImageUrl = "~/img/people/12.jpg",
                            Password = "B1gData&R3search",
                            PostStatisticsId = 1,
                            Username = "EthanWilliams"
                        });
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Comment", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Forum_MVC.Data.Entities.PostStatistics", "PostStatistics")
                        .WithOne()
                        .HasForeignKey("Forum_MVC.Data.Entities.Comment", "PostStatisticsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Forum_MVC.Data.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("PostStatistics");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Post", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.Category", "Categories")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Forum_MVC.Data.Entities.PostStatistics", "PostStatistics")
                        .WithOne()
                        .HasForeignKey("Forum_MVC.Data.Entities.Post", "PostStatisticsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Forum_MVC.Data.Entities.TopicOfPost", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicOfPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Forum_MVC.Data.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("PostStatistics");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.TopicOfPost", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.User", b =>
                {
                    b.HasOne("Forum_MVC.Data.Entities.PostStatistics", "PostStatistics")
                        .WithOne()
                        .HasForeignKey("Forum_MVC.Data.Entities.User", "PostStatisticsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PostStatistics");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.TopicOfPost", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Forum_MVC.Data.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
